version: '3.9'
services:
  web:
    container_name: web
    build: .
    ports:
      - 3000:3000
    links: 
      - "db:database"
  db:
    container_name: db
    image: couchbase
    ports:
      - 8091:8091
      # - 8092:8092
      # - 8093:8093
      # - 8094:8094
      # - 11210:11210
    volumes:
      - C:\Users\TIANGCO\Documents\Projects\couch-data:/opt/couchbase/var/